export const routes = {
  home: '/',
  ticket: '/buy-ticket',
  renting: '/rent-vehicle',
  rentalService: '/rent-vehicle/rental-service',
  rentalServiceDetail: '/rent-vehicle/rental-service/rental-service-detail',
  rentalOrder: '/rent-vehicle/rental-service/rental-service-detail/rental-order',
  booking: '/book-vehicle',
  bookingService: '/book-vehicle/booking-service',
  bookingOrder: '/book-vehicle/booking-service/booking-order',
  partner: '/register-partner',
  answer: '/answer-hub',
  about: '/about',
  accountSetting: '/account-setting',
  order: '/manage-orders',
  resetPassword: '/reset-password',
}