export { default as AuthCodeModal } from './AuthCodeModal'
export { default as ForgetPasswordModal } from './ForgetPasswordModal'
export { default as RegisterModal } from './RegisterModal'
export { default as PersonalModal } from './PersonalModal'
export { default as LoginModal } from './LoginModal'
export {default as RegisterAdminModal } from './RegisterAdminModal'
